workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install xcodegen
        script: brew install xcodegen
      - name: Generate Xcode project
        script: xcodegen generate
      - name: Build iOS
        script: |
          xcodebuild build \
            -project LoveKeyboard.xcodeproj \
            -scheme LoveKeyboard \
            -sdk iphonesimulator \
            -configuration Debug \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - build/ios/ipa/*.ipa
